# docker-compose.yml

version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: web-container
    depends_on:
      - db
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      DB_CONNECTIONSTRING: "postgres://example_user:example_password@db:5432/inventory_management"
      NEXTAUTH_URL: "http://localhost:3000/api/auth"
      NEXTAUTH_SECRET: "XRHdKuPodU2FiNRKZJ6ipcRag9KM4PwRwuj6k45BVdA="
  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: inventory_management
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  
volumes:
  db:
    driver: local